namespace CodesEnum {
	export enum Type {
		SIGN_IN = 'SIGN_IN',
		RECOVER_PASSWORD = 'RECOVER_PASSWORD',
		UPDATE_EMAIL = 'UPDATE_EMAIL',
		SIGN_IN_EMPLOYEE = 'SIGN_IN_EMPLOYEE',
		MANAGER_SIGN_IN = 'MANAGER_SIGN_IN',
		MANAGER_RECOVER_PASSWORD = 'MANAGER_RECOVER_PASSWORD',
	}
}

export default CodesEnum;
